name: beuty_app
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.1+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  #getx
  get:

  #network
  http: ^0.13.3
  dio: ^4.0.0


  #rating
  flutter_rating_bar: ^4.0.0

  #slider
  carousel_slider: ^4.0.0

  #image picker
  image_picker: ^0.8.2
  multi_image_picker: ^4.7.15
  flutter_absolute_path: ^1.0.6

  #slider up panel (like, bottom sheet)
  sliding_up_panel: ^2.0.0+1

  #google login
  google_sign_in: ^5.0.5

  #facebook login
#  flutter_facebook_login: ^3.0.0


  #firebase
  firebase_auth: ^3.0.1
  firebase_core: ^1.4.0
  cloud_firestore: ^2.4.0
  firebase_storage: ^10.0.1
  firebase_messaging: ^10.0.2
  firebase_dynamic_links: ^2.0.0


  #use in chat
  photo_view: ^0.12.0
  shared_preferences: ^2.0.6


  #charts
  syncfusion_flutter_charts: ^19.2.47

  #svg images
  flutter_svg: ^0.22.0

  #grid view
  flutter_staggered_grid_view: ^0.4.0

  #get storage
  get_storage: ^2.0.2

  #google map
  google_maps_flutter:
  flutter_polyline_points:

  #geolocator
  geolocator: ^7.3.0

  #image filter
  image_cropper: ^1.4.1
  photofilters: ^3.0.1
  image: ^3.0.2
  screenshot: ^1.2.3
  extended_image: ^4.1.0
  flutter_image_compress: ^1.1.0


  #path provider
  path_provider: ^2.0.2

  #dateformat
  intl: ^0.17.0

  #slidable
  flutter_slidable: ^0.6.0

  #datetime piker
  datetime_picker_formfield: ^2.0.0

  #octo image
  octo_image: ^1.0.0+1
  cached_network_image: ^3.1.0

  url_launcher: ^5.1.2
  share: ^2.0.4



  #stripe payment
  flutter_credit_card: ^0.1.3
  stripe_payment: ^1.0.7
  progress_dialog: ^1.2.2

  #expandable text
  expandable_text: 2.2.0

  #notification
  flutter_local_notifications: ^5.0.0+3

  #permission handler
  permission_handler: ^6.0.1

  #apple login
  apple_sign_in: ^0.1.0

  #Internet connection checker
  data_connection_checker: ^0.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/image/
    - assets/svg/

  #   - images/a_dot_ham.jpeg
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900

    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-Regular.ttf
          weight: 400
        - asset: assets/fonts/Manrope-Medium.ttf
          weight: 500
        - asset: assets/fonts/Manrope-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Manrope-Bold.ttf
          weight: 700
        - asset: assets/fonts/Manrope-ExtraBold.ttf
          weight: 800

